# -*- coding: utf-8 -*-
"""PFF v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsttvBBAfz23Y7MEzG9ZgnZmZ4YVLA89
"""

# 如果 Colab 里还没装 xlsxwriter，这行会自动安装
!pip -q install xlsxwriter

import pandas as pd
import re
import io
from google.colab import files
from IPython.display import display
from datetime import datetime

# =========================
# 1. 上传文件
# =========================
print("请一次上传 2 个 Excel 文件：")
print("1. Gary现场箱号表")
print("2. 任务明细导出表（含 运单号 / 领取状态 / 派送方 / 箱号 等字段）")
uploaded = files.upload()

if len(uploaded) < 2:
    raise ValueError("请至少上传 2 个文件。")

print("\n已上传文件：")
for k in uploaded.keys():
    print("-", k)

# =========================
# 2. 基础配置
# =========================
PFF_ZONES = {"F3", "F4", "F5", "F11", "F12", "F13"}

# =========================
# 3. 工具函数
# =========================
def clean_box_no(x):
    if pd.isna(x):
        return None
    x = str(x).strip().upper().replace(" ", "")
    m = re.search(r'B\d{13}', x)
    return m.group(0) if m else None

def standardize_columns(df):
    df.columns = (
        pd.Index(df.columns)
        .astype(str)
        .str.strip()
        .str.replace("\n", "", regex=False)
        .str.replace("\r", "", regex=False)
    )
    return df

def try_read_excel_from_bytes(file_bytes, header_option):
    return pd.read_excel(io.BytesIO(file_bytes), header=header_option)

def normalize_text(x):
    if pd.isna(x):
        return ""
    return str(x).strip()

def normalize_upper_text(x):
    return normalize_text(x).upper()

def contains_unpicked(text):
    return "未领" in normalize_text(text)

def extract_f_zone(x):
    """
    从以下格式提取 F区：
    - F13
    - F13-7
    - MIA01-F13-
    - MIA01-F13-xxx
    """
    s = normalize_upper_text(x).replace(" ", "")
    m = re.search(r'F\d+', s)
    return m.group(0) if m else ""

def ratio_match(series, pattern_func, sample_size=200):
    s = series.dropna().astype(str).head(sample_size)
    if len(s) == 0:
        return 0
    return sum(pattern_func(v) for v in s) / len(s)

def is_box_value(x):
    s = str(x).strip().upper().replace(" ", "")
    return bool(re.fullmatch(r'B\d{13}', s))

def is_route_stop_value(x):
    s = str(x).strip().upper().replace(" ", "")
    return bool(re.fullmatch(r'F\d+-\d+', s))

def is_route_value(x):
    s = str(x).strip().upper().replace(" ", "")
    return bool(re.fullmatch(r'F\d+', s))

def is_numeric_value(x):
    s = str(x).strip()
    return bool(re.fullmatch(r'\d+', s))

def find_best_col_by_name(columns, candidates):
    cols = list(columns)

    def norm(s):
        return str(s).strip().lower().replace("_", "").replace("-", "").replace(" ", "")

    norm_map = {c: norm(c) for c in cols}

    # 原始精确匹配
    for cand in candidates:
        cand_raw = str(cand).strip().lower()
        for c in cols:
            if str(c).strip().lower() == cand_raw:
                return c

    # 标准化后精确匹配
    for cand in candidates:
        cand_norm = norm(cand)
        for c, c_norm in norm_map.items():
            if c_norm == cand_norm:
                return c

    # 最后才模糊匹配
    for cand in candidates:
        cand_norm = norm(cand)
        for c, c_norm in norm_map.items():
            if cand_norm in c_norm:
                return c

    return None

# =========================
# 4. Gary 表识别
# =========================
def detect_gary_columns(df):
    cols = list(df.columns)

    box_col = find_best_col_by_name(cols, [
        "box no", "box", "bag", "bag no", "箱号", "袋号"
    ])
    route_stop_col = find_best_col_by_name(cols, [
        "route-stop", "route stop", "stop"
    ])
    address_col = find_best_col_by_name(cols, [
        "address", "地址"
    ])
    count_col = find_best_col_by_name(cols, [
        "count", "数量", "件数", "qty"
    ])

    # route 列先按列名找
    route_col = find_best_col_by_name(cols, ["route", "路线"])

    # 如果没找到 route，就按内容特征找像 F13 的列
    if route_col is None:
        scores = []
        for c in cols:
            if c in [box_col, route_stop_col, address_col, count_col]:
                continue
            score = ratio_match(df[c], is_route_value)
            scores.append((c, score))
        best = max(scores, key=lambda x: x[1], default=(None, 0))
        if best[1] >= 0.3:
            route_col = best[0]

    # 内容补识别
    if box_col is None:
        scores = [(c, ratio_match(df[c], is_box_value)) for c in cols]
        best = max(scores, key=lambda x: x[1], default=(None, 0))
        if best[1] >= 0.3:
            box_col = best[0]

    if route_stop_col is None:
        scores = [(c, ratio_match(df[c], is_route_stop_value)) for c in cols if c != box_col]
        best = max(scores, key=lambda x: x[1], default=(None, 0))
        if best[1] >= 0.3:
            route_stop_col = best[0]

    if count_col is None:
        scores = [(c, ratio_match(df[c], is_numeric_value)) for c in cols if c not in [box_col, route_stop_col, route_col]]
        best = max(scores, key=lambda x: x[1], default=(None, 0))
        if best[1] >= 0.5:
            count_col = best[0]

    if route_col == route_stop_col:
        route_col = None

    return {
        "box_col": box_col,
        "route_stop_col": route_stop_col,
        "route_col": route_col,
        "address_col": address_col,
        "count_col": count_col
    }

def load_onsite_from_bytes(file_bytes, file_name=""):
    for h in [0, 1, 2, 3, 4, 5]:
        try:
            df = try_read_excel_from_bytes(file_bytes, h)
            df = standardize_columns(df)
            detected = detect_gary_columns(df)

            if detected["box_col"] is not None:
                result = df.copy()
                result["box no"] = result[detected["box_col"]]
                result["box_no_clean"] = result["box no"].apply(clean_box_no)
                result = result[result["box_no_clean"].notna()].copy()

                if detected["route_stop_col"]:
                    result["route-stop"] = result[detected["route_stop_col"]].astype(str)
                else:
                    result["route-stop"] = ""

                if detected["route_col"]:
                    result["route"] = result[detected["route_col"]].astype(str)
                else:
                    result["route"] = result["route-stop"].apply(extract_f_zone)

                if detected["address_col"]:
                    result["address"] = result[detected["address_col"]]
                else:
                    result["address"] = ""

                if detected["count_col"]:
                    result["count"] = result[detected["count_col"]]
                else:
                    result["count"] = 0

                result = result.drop_duplicates(subset=["box_no_clean"])

                print(f"[现场箱号表识别成功] {file_name} | header={h}")
                print("识别列：", detected)
                return result
        except:
            pass

    raise ValueError(f"无法识别为 Gary现场箱号表：{file_name}")

# =========================
# 5. 任务表识别
# =========================
def looks_like_task_df(df):
    needed = {"运单号", "领取状态", "派送方", "快递员区域名称", "快递员路线", "箱号"}
    return len(needed.intersection(set(df.columns))) >= 4

def load_task_from_bytes(file_bytes, file_name=""):
    for h in [0, 1, 2, 3, 4, 5]:
        try:
            df = try_read_excel_from_bytes(file_bytes, h)
            df = standardize_columns(df)

            if looks_like_task_df(df):
                needed_cols = ["运单号", "领取状态", "派送方", "快递员区域名称", "快递员路线", "箱号"]
                missing = [c for c in needed_cols if c not in df.columns]
                if missing:
                    continue

                result = df.copy()
                result["box_no_clean"] = result["箱号"].apply(clean_box_no)
                result["vendor_clean"] = result["派送方"].apply(normalize_upper_text)
                result["pickup_status_clean"] = result["领取状态"].apply(normalize_text)
                result["zone_clean"] = result["快递员区域名称"].apply(extract_f_zone)
                result["route_clean"] = result["快递员路线"].apply(extract_f_zone)

                result = result[result["box_no_clean"].notna()].copy()
                result = result[result["vendor_clean"].str.contains("PFF", na=False)].copy()
                result = result[result["zone_clean"].isin(PFF_ZONES)].copy()
                result = result[result["pickup_status_clean"].apply(contains_unpicked)].copy()

                print(f"[任务表识别成功] {file_name} | header={h}")
                return result
        except:
            pass

    raise ValueError(f"无法识别为任务表：{file_name}")

# =========================
# 6. 自动识别文件
# =========================
onsite_df = None
task_df = None
onsite_name = None
task_name = None

for fname, fbytes in uploaded.items():
    if onsite_df is None:
        try:
            onsite_df = load_onsite_from_bytes(fbytes, fname)
            onsite_name = fname
            continue
        except:
            pass

    if task_df is None:
        try:
            task_df = load_task_from_bytes(fbytes, fname)
            task_name = fname
            continue
        except:
            pass

if onsite_df is None or task_df is None:
    for fname, fbytes in uploaded.items():
        if onsite_df is None:
            try:
                onsite_df = load_onsite_from_bytes(fbytes, fname)
                onsite_name = fname
            except:
                pass
        if task_df is None:
            try:
                task_df = load_task_from_bytes(fbytes, fname)
                task_name = fname
            except:
                pass

if onsite_df is None:
    raise ValueError("没有识别出 Gary现场箱号表。")
if task_df is None:
    raise ValueError("没有识别出任务表。")

print("\n最终识别结果：")
print("现场箱号表：", onsite_name)
print("任务表：", task_name)

# =========================
# 7. 比对逻辑
# =========================
def compare_files(onsite_df, task_df):
    print("\n[DEBUG] onsite_df columns:", onsite_df.columns.tolist())
    print("[DEBUG] task_df columns:", task_df.columns.tolist())

    keep_cols = [
        "运单号", "箱号", "box_no_clean", "派送方", "领取状态",
        "快递员区域名称", "快递员路线", "zone_clean", "route_clean"
    ]
    keep_cols = [c for c in keep_cols if c in task_df.columns]

    matched_df = onsite_df.merge(
        task_df[keep_cols].copy(),
        on="box_no_clean",
        how="inner"
    )

    matched_df["issue_flag"] = "现场有但任务表仍未领"
    display_df = matched_df.drop_duplicates(subset=["box_no_clean"]).copy()
    return matched_df, display_df

def build_route_summary(display_df):
    if display_df.empty:
        return pd.DataFrame(columns=["route", "issue_boxes", "affected_packages"])

    temp = display_df.copy()
    temp["count_num"] = pd.to_numeric(temp["count"], errors="coerce").fillna(0)

    route_summary = (
        temp.groupby("route", dropna=False)
        .agg(
            issue_boxes=("box_no_clean", "nunique"),
            affected_packages=("count_num", "sum")
        )
        .reset_index()
        .sort_values(by=["issue_boxes", "affected_packages"], ascending=False)
    )
    return route_summary

def build_summary_text(display_df):
    if display_df.empty:
        return "PFF现场领件检查结果：\n\n未发现现场到货箱号仍处于未领状态。"

    issue_boxes = display_df["box_no_clean"].nunique()
    affected_packages = pd.to_numeric(display_df["count"], errors="coerce").fillna(0).sum()

    return "\n".join([
        "PFF现场领件检查结果：",
        "",
        f"共发现 {issue_boxes} 个现场到货箱号仍处于未领状态，涉及 {int(affected_packages)} 件包裹。",
        "请站点经理和司机立即现场核查并完成补领。"
    ])

matched_df, display_df = compare_files(onsite_df, task_df)
route_summary = build_route_summary(display_df)
summary_text = build_summary_text(display_df)

onsite_boxes = onsite_df["box_no_clean"].nunique()
unpicked_boxes = task_df["box_no_clean"].nunique()
issue_boxes = display_df["box_no_clean"].nunique()
affected_packages = pd.to_numeric(display_df["count"], errors="coerce").fillna(0).sum()

# =========================
# 8. 输出结果
# =========================
print("\n=== PFF Pickup Check Result ===")
print(f"Onsite Boxes: {onsite_boxes}")
print(f"Unpicked Boxes (from task file): {unpicked_boxes}")
print(f"Issue Boxes: {issue_boxes}")
print(f"Affected Packages: {int(affected_packages)}")
print()
print(summary_text)

print("\n=== Issue Box List ===")
if display_df.empty:
    print("No onsite boxes are still marked as unpicked.")
else:
    cols_to_show = [
        "box no", "route-stop", "route", "address", "count", "box_no_clean",
        "快递员区域名称", "快递员路线", "领取状态"
    ]
    cols_to_show = [c for c in cols_to_show if c in display_df.columns]
    display(display_df[cols_to_show])

print("\n=== Route Summary ===")
display(route_summary)

# =========================
# 9. 导出 Excel
# =========================
today_str = datetime.today().strftime("%Y%m%d")
output_file = f"PFF_Pickup_Check_{today_str}.xlsx"

with pd.ExcelWriter(output_file, engine="xlsxwriter") as writer:
    onsite_df.to_excel(writer, sheet_name="onsite_boxes", index=False)
    task_df.to_excel(writer, sheet_name="task_unpicked_boxes", index=False)
    matched_df.to_excel(writer, sheet_name="matched_raw", index=False)
    display_df.to_excel(writer, sheet_name="issue_boxes", index=False)
    route_summary.to_excel(writer, sheet_name="route_summary", index=False)
    pd.DataFrame({"summary": summary_text.split("\n")}).to_excel(
        writer, sheet_name="summary", index=False
    )

print(f"\n结果文件已生成：{output_file}")
files.download(output_file)